#!/usr/bin/env python3
"""C13-B: learn a bounded-local-observation ranker from feasible rollouts.

The supervision in this module is deliberately not an optimal cost-to-go.
Trajectories are generated by a behavior policy that can inspect only the
current node's outgoing edges, Euclidean goal geometry, and its own visit
history.  Each labeled node receives independent rollouts with visit history
reset; only that node's fresh-start Monte Carlo return is used.  Repeated
returns for a state are aggregated by the median, never the minimum, so the
collector does not turn repeated exploration into a shortest-path solver.

The learned return is not assumed admissible.  Its primary planner integration
is therefore as a secondary rank inside a FOCAL set whose membership is defined
by admissible Euclidean A*.  Dijkstra remains confined to PRM connectivity
filtering and evaluation; it is not a label, feature, policy input, or model
input.
"""
from __future__ import annotations

import argparse
import json
import math
import random
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, DefaultDict, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

import continuous_prm_common as C
import continuous_prm_c13_state_heuristic as C13
import continuous_prm_c7_hard_maps as M7
from continuous_prm_focal import focal_astar_search


TARGET_SOURCE = "successful_fresh_start_local_behavior_rollout_return_mc"
TARGET_AGGREGATION = "median_successful_fresh_start_realized_return"
TARGET_TRANSFORM = "log1p_normalized_return_excess_over_euclidean"
SHORTEST_PATH_TARGET = False
ORACLE_POLICY_ACCESS = False


@dataclass(frozen=True)
class RolloutPolicyConfig:
    """One-hop behavior-policy controls.

    The policy's only persistent state is visit history.  It cannot inspect a
    successor's successors before moving there.
    """

    rollouts_per_start: int = 3
    max_steps_factor: int = 12
    epsilon: float = 0.02
    temperature: float = 0.02
    revisit_penalty_frac: float = 0.50
    reverse_penalty_frac: float = 0.15
    max_norm_residual: float = 4.0


@dataclass
class C13TDConfig:
    mode: str = "full"
    out_dir: str = "runs/c13_td_ranker"
    train_suites: str = "C_hard_maze,C_hard_rooms,C_hard_spiral"
    eval_suites: str = (
        "C_hard_maze,C_hard_maze_dense,C_hard_rooms,"
        "C_hard_spiral,C_hard_bugtrap,C_hard_rooms_large"
    )
    train_worlds: int = 96
    val_worlds: int = 24
    eval_worlds: int = 24
    train_nodes: int = 192
    density_nodes: str = "128,160,192,211,256"
    roadmap_k: int = 7
    budgets: str = "96,144,192"
    focal_ws: str = "1.05,1.10,1.25"
    models: str = "hrm,onlstm"
    seed: int = 1234
    max_world_retries: int = 200
    sensor_radius_frac: float = 0.20
    num_rays: int = 16
    ray_steps: int = 24
    max_neighbors: int = 24
    rollouts_per_start: int = 3
    max_steps_factor: int = 12
    rollout_epsilon: float = 0.02
    rollout_temperature: float = 0.02
    revisit_penalty_frac: float = 0.50
    reverse_penalty_frac: float = 0.15
    max_norm_residual: float = 4.0
    min_labeled_nodes: int = 8
    batch_size: int = 128
    epochs: int = 12
    lr: float = 2.0e-4
    weight_decay: float = 1.0e-4
    grad_clip: float = 1.0
    hrm_hidden: int = 128
    hrm_layers: int = 2
    hrm_k_step: int = 2
    hrm_heads: int = 4
    onlstm_hidden: int = 128
    onlstm_layers: int = 2
    onlstm_chunk_size: int = 8
    head_hidden: int = 128
    device: str = "auto"
    smoke_test: bool = False

    def state_cfg(self) -> C13.LocalStateConfig:
        return C13.LocalStateConfig(
            sensor_radius_frac=float(self.sensor_radius_frac),
            num_rays=int(self.num_rays),
            ray_steps=int(self.ray_steps),
            max_neighbors=int(self.max_neighbors),
        )

    def policy_cfg(self) -> RolloutPolicyConfig:
        return RolloutPolicyConfig(
            rollouts_per_start=int(self.rollouts_per_start),
            max_steps_factor=int(self.max_steps_factor),
            epsilon=float(self.rollout_epsilon),
            temperature=float(self.rollout_temperature),
            revisit_penalty_frac=float(self.revisit_penalty_frac),
            reverse_penalty_frac=float(self.reverse_penalty_frac),
            max_norm_residual=float(self.max_norm_residual),
        )


def apply_smoke_overrides(cfg: C13TDConfig) -> C13TDConfig:
    if not cfg.smoke_test:
        return cfg
    cfg.train_suites = "C_hard_maze"
    cfg.eval_suites = "C_hard_maze"
    cfg.train_worlds = 3
    cfg.val_worlds = 1
    cfg.eval_worlds = 3
    cfg.train_nodes = 192
    cfg.density_nodes = "192,211"
    cfg.roadmap_k = 7
    cfg.budgets = "96,192"
    cfg.focal_ws = "1.10"
    cfg.rollouts_per_start = 3
    cfg.max_steps_factor = 8
    cfg.num_rays = 8
    cfg.ray_steps = 8
    cfg.max_neighbors = 16
    cfg.batch_size = 64
    cfg.epochs = 8
    cfg.lr = 1.0e-3
    cfg.hrm_hidden = 32
    cfg.hrm_layers = 1
    cfg.hrm_heads = 4
    cfg.onlstm_hidden = 32
    cfg.onlstm_layers = 1
    cfg.onlstm_chunk_size = 8
    cfg.head_hidden = 32
    return cfg


# ---------------------------------------------------------------------------
# Local behavior rollouts and Monte Carlo returns
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RolloutEpisode:
    nodes: Tuple[int, ...]
    edge_costs: Tuple[float, ...]
    found: bool

    @property
    def steps(self) -> int:
        return len(self.edge_costs)

    @property
    def total_cost(self) -> float:
        return float(sum(self.edge_costs))


def _weighted_choice(rng: random.Random, items: Sequence[int], weights: Sequence[float]) -> int:
    if len(items) != len(weights) or not items:
        raise ValueError("weighted choice requires equally sized non-empty inputs")
    total = float(sum(max(0.0, float(w)) for w in weights))
    if not math.isfinite(total) or total <= 0.0:
        return int(items[rng.randrange(len(items))])
    threshold = rng.random() * total
    running = 0.0
    for item, weight in zip(items, weights):
        running += max(0.0, float(weight))
        if running >= threshold:
            return int(item)
    return int(items[-1])


def local_behavior_rollout(
    points: np.ndarray,
    adj: Sequence[Sequence[Tuple[int, float]]],
    start_idx: int,
    side_len: float,
    rng: random.Random,
    cfg: RolloutPolicyConfig,
    goal_idx: int = 1,
) -> RolloutEpisode:
    """Execute a stochastic policy using only current one-hop information.

    Euclidean distance is evaluated for the currently visible actions.  The
    policy does not inspect adjacency lists belonging to nodes it has not yet
    visited and does not call any graph-search routine.
    """

    pts = np.asarray(points, dtype=np.float64)
    n = len(pts)
    if len(adj) != n:
        raise ValueError("points and adjacency size differ")
    if not (0 <= int(start_idx) < n and 0 <= int(goal_idx) < n):
        raise IndexError("start or goal index outside graph")
    if float(side_len) <= 0.0:
        raise ValueError("side_len must be positive")

    current = int(start_idx)
    nodes = [current]
    edge_costs: List[float] = []
    visits = np.zeros(n, dtype=np.int32)
    visits[current] = 1
    max_steps = max(1, int(cfg.max_steps_factor) * n)
    previous: Optional[int] = None
    goal = pts[int(goal_idx)]

    for _ in range(max_steps):
        if current == int(goal_idx):
            return RolloutEpisode(tuple(nodes), tuple(edge_costs), True)
        nbrs = [(int(v), float(w)) for v, w in adj[current] if float(w) >= 0.0]
        if not nbrs:
            break

        candidates = [v for v, _ in nbrs]
        if rng.random() < float(cfg.epsilon):
            # Exploration still disfavors repeatedly cycling through one node.
            weights = [1.0 / (1.0 + float(visits[v])) for v in candidates]
        else:
            scores: List[float] = []
            for v, edge_cost in nbrs:
                score = (
                    edge_cost / float(side_len)
                    + float(np.linalg.norm(pts[v] - goal)) / float(side_len)
                    + float(cfg.revisit_penalty_frac) * float(visits[v])
                )
                if previous is not None and v == previous and len(nbrs) > 1:
                    score += float(cfg.reverse_penalty_frac)
                scores.append(score)
            minimum = min(scores)
            temperature = max(1.0e-6, float(cfg.temperature))
            weights = [math.exp(-min(60.0, (score - minimum) / temperature)) for score in scores]

        chosen = _weighted_choice(rng, candidates, weights)
        edge_cost = next(w for v, w in nbrs if v == chosen)
        previous, current = current, chosen
        nodes.append(current)
        edge_costs.append(float(edge_cost))
        visits[current] += 1

    return RolloutEpisode(tuple(nodes), tuple(edge_costs), current == int(goal_idx))


def realized_returns(episode: RolloutEpisode) -> np.ndarray:
    """Return the undiscounted suffix cost at every visited state."""

    if len(episode.nodes) != len(episode.edge_costs) + 1:
        raise ValueError("episode must contain one more node than edge costs")
    returns = np.zeros(len(episode.nodes), dtype=np.float64)
    running = 0.0
    for idx in range(len(episode.edge_costs) - 1, -1, -1):
        running += float(episode.edge_costs[idx])
        returns[idx] = running
    return returns


def aggregate_all_visit_returns_for_audit(
    episodes: Iterable[RolloutEpisode],
) -> Tuple[Dict[int, float], Dict[int, int], Dict[str, Any]]:
    """Audit every visited-state return; this is not a training target."""

    values: DefaultDict[int, List[float]] = defaultdict(list)
    total = 0
    successes = 0
    steps: List[int] = []
    costs: List[float] = []
    for episode in episodes:
        total += 1
        if not episode.found:
            continue
        successes += 1
        returns = realized_returns(episode)
        for node, value in zip(episode.nodes, returns):
            values[int(node)].append(float(value))
        steps.append(episode.steps)
        costs.append(episode.total_cost)
    medians = {node: float(np.median(samples)) for node, samples in values.items()}
    counts = {node: len(samples) for node, samples in values.items()}
    stats = {
        "episodes": total,
        "successful_episodes": successes,
        "success_rate": successes / max(1, total),
        "labeled_nodes": len(medians),
        "successful_steps_mean": float(np.mean(steps)) if steps else float("nan"),
        "successful_cost_mean": float(np.mean(costs)) if costs else float("nan"),
        "aggregation": "median_all_visit_return_audit_only",
    }
    return medians, counts, stats

def aggregate_successful_start_returns(
    episodes_by_start: Mapping[int, Sequence[RolloutEpisode]],
) -> Tuple[Dict[int, float], Dict[int, int], Dict[str, Any]]:
    """Aggregate only fresh-start returns, so hidden visit history cannot alias labels."""

    medians: Dict[int, float] = {}
    counts: Dict[int, int] = {}
    total = 0
    successes = 0
    steps: List[int] = []
    costs: List[float] = []
    for start, episodes in episodes_by_start.items():
        successful_costs: List[float] = []
        for episode in episodes:
            total += 1
            if not episode.found:
                continue
            successes += 1
            successful_costs.append(episode.total_cost)
            steps.append(episode.steps)
            costs.append(episode.total_cost)
        if successful_costs:
            medians[int(start)] = float(np.median(successful_costs))
            counts[int(start)] = len(successful_costs)
    stats = {
        "episodes": total,
        "successful_episodes": successes,
        "success_rate": successes / max(1, total),
        "labeled_nodes": len(medians),
        "successful_steps_mean": float(np.mean(steps)) if steps else float("nan"),
        "successful_cost_mean": float(np.mean(costs)) if costs else float("nan"),
        "aggregation": TARGET_AGGREGATION,
        "history_condition": "visit_history_reset_at_each_labeled_start",
    }
    return medians, counts, stats



def collect_rollout_targets_from_roadmap(
    roadmap: Any,
    side_len: float,
    rng: random.Random,
    cfg: RolloutPolicyConfig,
    goal_idx: int = 1,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[str, Any]]:
    """Collect targets while deliberately reading only ``points`` and ``adj``.

    Accepting a roadmap-like object makes the no-oracle property testable: a
    sentinel ``dist_to_goal`` property can raise if this function ever touches
    it.
    """

    points = np.asarray(roadmap.points, dtype=np.float64)
    adj = roadmap.adj
    n = len(points)
    episodes_by_start: Dict[int, List[RolloutEpisode]] = {
        start: [
            local_behavior_rollout(points, adj, start, side_len, rng, cfg, goal_idx=goal_idx)
            for _ in range(max(1, int(cfg.rollouts_per_start)))
        ]
        for start in range(n)
    }
    returns_by_node, counts_by_node, stats = aggregate_successful_start_returns(episodes_by_start)
    node_indices = np.array(sorted(returns_by_node), dtype=np.int64)
    returns = np.array([returns_by_node[int(i)] for i in node_indices], dtype=np.float64)
    counts = np.array([counts_by_node[int(i)] for i in node_indices], dtype=np.int32)
    return node_indices, returns, counts, stats


def rollout_residual_targets(
    points: np.ndarray,
    node_indices: np.ndarray,
    realized_costs: np.ndarray,
    side_len: float,
    max_norm_residual: float,
    goal_idx: int = 1,
) -> Tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(points, dtype=np.float64)
    indices = np.asarray(node_indices, dtype=np.int64)
    costs = np.asarray(realized_costs, dtype=np.float64)
    euclid = C13.euclidean_to_goal(pts, pts[int(goal_idx)])[indices]
    raw = np.maximum(0.0, costs - euclid) / max(C.EPS, float(side_len))
    transformed = np.log1p(raw)
    clipped = np.clip(transformed, 0.0, float(max_norm_residual))
    return clipped.astype(np.float32), raw.astype(np.float32)


# ---------------------------------------------------------------------------
# Dataset collection
# ---------------------------------------------------------------------------


def collect_rollout_dataset(
    cfg: C13TDConfig,
    split: str,
    suites: Sequence[str],
    worlds_per_suite: int,
    seed_offset: int,
) -> Path:
    M7.install_c7_hard_maps()
    specs = C.build_anchor_specs()
    state_cfg = cfg.state_cfg()
    policy_cfg = cfg.policy_cfg()
    xs: List[np.ndarray] = []
    ys: List[np.ndarray] = []
    raw_ys: List[np.ndarray] = []
    counts_all: List[np.ndarray] = []
    world_ids: List[np.ndarray] = []
    records: List[Dict[str, Any]] = []
    global_world_id = 0

    for suite_idx, suite in enumerate(suites):
        if suite not in specs:
            raise KeyError(f"unknown suite {suite!r}; have {sorted(specs)}")
        accepted = 0
        candidate_worlds = int(worlds_per_suite) * int(cfg.max_world_retries)
        for _, world, world_seed in C13.iter_worlds(
            specs[suite],
            suite_idx,
            candidate_worlds,
            int(cfg.seed) + int(seed_offset),
            retry=cfg.max_world_retries,
        ):
            rm = C.build_prm(
                world,
                C.RoadmapConfig(n_nodes=int(cfg.train_nodes), k_neighbors=int(cfg.roadmap_k)),
                seed=world_seed + 17,
            )
            if rm is None:
                continue
            rollout_seed = world_seed + 71_003 + int(seed_offset)
            indices, returns, counts, rollout_stats = collect_rollout_targets_from_roadmap(
                rm,
                world.side_len,
                random.Random(rollout_seed),
                policy_cfg,
            )
            if len(indices) < int(cfg.min_labeled_nodes):
                continue
            all_features = C13.make_local_state_features(world, rm.points, rm.adj, state_cfg)
            target, raw_target = rollout_residual_targets(
                rm.points,
                indices,
                returns,
                world.side_len,
                policy_cfg.max_norm_residual,
            )
            xs.append(all_features[indices])
            ys.append(target)
            raw_ys.append(raw_target)
            counts_all.append(counts)
            world_ids.append(np.full(len(indices), global_world_id, dtype=np.int32))
            records.append(
                {
                    "world_id": global_world_id,
                    "suite": suite,
                    "suite_world_index": accepted,
                    "world_seed": world_seed,
                    "roadmap_seed": world_seed + 17,
                    "rollout_seed": rollout_seed,
                    "nodes": len(rm.points),
                    "edges": sum(len(a) for a in rm.adj) // 2,
                    "samples": len(indices),
                    "coverage_rate": len(indices) / max(1, len(rm.points)),
                    "target_mean": float(np.mean(target)),
                    "target_clip_rate": float(
                        np.mean(np.log1p(raw_target) > policy_cfg.max_norm_residual)
                    ),
                    **rollout_stats,
                }
            )
            global_world_id += 1
            accepted += 1
            if accepted >= int(worlds_per_suite):
                break
        if accepted < int(worlds_per_suite):
            raise RuntimeError(f"{split}/{suite} under-filled: {accepted}/{worlds_per_suite}")

    if not xs:
        raise RuntimeError(f"no C13-B samples collected for split {split!r}")
    dataset_dir = C13.ensure_dir(Path(cfg.out_dir) / "datasets")
    path = dataset_dir / f"c13_td_{split}.npz"
    np.savez_compressed(
        path,
        x=np.concatenate(xs).astype(np.float32),
        y=np.concatenate(ys).astype(np.float32),
        raw_y=np.concatenate(raw_ys).astype(np.float32),
        rollout_count=np.concatenate(counts_all).astype(np.int32),
        world_id=np.concatenate(world_ids).astype(np.int32),
    )
    metadata = {
        "experiment": "C13-B",
        "split": split,
        "target_source": TARGET_SOURCE,
        "target_aggregation": TARGET_AGGREGATION,
        "target_transform": TARGET_TRANSFORM,
        "max_log_residual": float(cfg.max_norm_residual),
        "shortest_path_target": SHORTEST_PATH_TARGET,
        "oracle_policy_access": ORACLE_POLICY_ACCESS,
        "shortest_path_result_used_as_input": False,
        "dijkstra_role": "roadmap_connectivity_filter_and_evaluation_only",
        "behavior_policy_scope": "current_one_hop_actions_goal_geometry_visit_history",
        "label_history_condition": "fresh_start_zero_visit_history_only",
        "runtime_model_scope": "current_geometry_bounded_rays_one_hop_actions",
        "forbidden_inputs": list(C13.FORBIDDEN_INPUTS),
        "state_config": asdict(state_cfg),
        "rollout_policy": asdict(policy_cfg),
        "roadmap_nodes": int(cfg.train_nodes),
        "roadmap_k": int(cfg.roadmap_k),
        "suites": list(suites),
        "worlds": records,
        "n_samples": int(sum(len(y) for y in ys)),
    }
    C13.write_json(path.with_suffix(".metadata.json"), metadata)
    return path


# ---------------------------------------------------------------------------
# HRM / ON-LSTM regression
# ---------------------------------------------------------------------------


def model_configs(cfg: C13TDConfig) -> Dict[str, C.BackboneConfig]:
    return {
        "hrm": C.BackboneConfig(
            name="hrm",
            backbone_type="hrm",
            hidden_dim=int(cfg.hrm_hidden),
            num_layers=int(cfg.hrm_layers),
            k_step=int(cfg.hrm_k_step),
            num_heads=int(cfg.hrm_heads),
            head_hidden=int(cfg.head_hidden),
        ),
        "onlstm": C.BackboneConfig(
            name="onlstm",
            backbone_type="onlstm",
            hidden_dim=int(cfg.onlstm_hidden),
            num_layers=int(cfg.onlstm_layers),
            chunk_size=int(cfg.onlstm_chunk_size),
            head_hidden=int(cfg.head_hidden),
        ),
    }


def resolve_device(name: str) -> torch.device:
    if str(name).lower() == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def _load_dataset(path: Path) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    with np.load(path) as data:
        x = data["x"].astype(np.float32)
        y = data["y"].astype(np.float32)
        counts = data["rollout_count"].astype(np.float32)
    weights = np.clip(np.sqrt(np.maximum(1.0, counts)), 1.0, 4.0).astype(np.float32)
    weights /= max(C.EPS, float(np.mean(weights)))
    return x, y, weights


def _regression_metrics(model: torch.nn.Module, x: np.ndarray, y: np.ndarray, device: torch.device) -> Dict[str, float]:
    prediction = C.predict_norm_residuals(model, x, device, batch_size=512)
    error = prediction - y.astype(np.float64)
    corr = float("nan")
    if len(y) > 2 and np.std(prediction) > 1.0e-8 and np.std(y) > 1.0e-8:
        corr = float(np.corrcoef(prediction, y)[0, 1])
    return {
        "mae": float(np.mean(np.abs(error))),
        "rmse": float(np.sqrt(np.mean(error * error))),
        "corr": corr,
        "prediction_mean": float(np.mean(prediction)),
        "target_mean": float(np.mean(y)),
    }


def train_ranker(
    cfg: C13TDConfig,
    model_name: str,
    train_path: Path,
    val_path: Path,
    device: torch.device,
) -> Path:
    configs = model_configs(cfg)
    if model_name not in configs:
        raise KeyError(f"unknown model {model_name!r}; have {sorted(configs)}")
    backbone_cfg = configs[model_name]
    x_train, y_train, weights = _load_dataset(train_path)
    x_val, y_val, _ = _load_dataset(val_path)
    C.set_global_seed(int(cfg.seed) + (17 if model_name == "hrm" else 29))
    model = C.ContinuousHeuristicModel(
        backbone_cfg,
        token_dim=int(cfg.state_cfg().token_dim),
        max_norm_residual=float(cfg.max_norm_residual),
    ).to(device)
    ds = TensorDataset(
        torch.from_numpy(x_train),
        torch.from_numpy(y_train),
        torch.from_numpy(weights),
    )
    loader = DataLoader(ds, batch_size=int(cfg.batch_size), shuffle=True, num_workers=0)
    optimizer = torch.optim.AdamW(model.parameters(), lr=float(cfg.lr), weight_decay=float(cfg.weight_decay))
    C.set_global_seed(int(cfg.seed) + (17 if model_name == "hrm" else 29))
    history: List[Dict[str, Any]] = []

    for epoch in range(1, int(cfg.epochs) + 1):
        model.train()
        losses: List[float] = []
        t0 = time.perf_counter()
        for xb, yb, wb in loader:
            xb = xb.to(device)
            yb = yb.to(device)
            wb = wb.to(device)
            optimizer.zero_grad(set_to_none=True)
            pred = model(xb)
            per_sample = F.smooth_l1_loss(pred, yb, reduction="none")
            loss = torch.sum(per_sample * wb) / torch.clamp(torch.sum(wb), min=C.EPS)
            if not torch.isfinite(loss):
                raise RuntimeError(f"nonfinite C13-B loss for {model_name}")
            loss.backward()
            if float(cfg.grad_clip) > 0.0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), float(cfg.grad_clip))
            optimizer.step()
            losses.append(float(loss.item()))
        val_metrics = _regression_metrics(model, x_val, y_val, device)
        row = {
            "epoch": epoch,
            "train_loss": float(np.mean(losses)),
            "seconds": time.perf_counter() - t0,
            **{f"val_{key}": value for key, value in val_metrics.items()},
        }
        history.append(row)
        print(
            f"C13-B {model_name} epoch {epoch}/{cfg.epochs}: "
            f"loss={row['train_loss']:.5f} val_mae={row['val_mae']:.5f}",
            flush=True,
        )

    checkpoint_dir = C13.ensure_dir(Path(cfg.out_dir) / "checkpoints")
    checkpoint = checkpoint_dir / f"c13_td_{model_name}.pt"
    payload = {
        "model": model.state_dict(),
        "experiment": "C13-B",
        "model_name": model_name,
        "backbone_cfg": asdict(backbone_cfg),
        "state_cfg": asdict(cfg.state_cfg()),
        "target_source": TARGET_SOURCE,
        "target_aggregation": TARGET_AGGREGATION,
        "target_transform": TARGET_TRANSFORM,
        "shortest_path_target": SHORTEST_PATH_TARGET,
        "oracle_policy_access": ORACLE_POLICY_ACCESS,
        "max_log_residual": float(cfg.max_norm_residual),
        "history": history,
    }
    torch.save(payload, checkpoint)
    C13.write_json(
        Path(cfg.out_dir) / "logs" / f"train_c13_td_{model_name}.json",
        {key: value for key, value in payload.items() if key != "model"},
    )
    return checkpoint


def load_ranker(cfg: C13TDConfig, model_name: str, checkpoint: Path, device: torch.device) -> torch.nn.Module:
    payload = torch.load(checkpoint, map_location="cpu")
    if payload.get("shortest_path_target") is not False:
        raise ValueError(f"checkpoint {checkpoint} lacks the C13-B no-shortest-path provenance flag")
    if payload.get("target_transform") != TARGET_TRANSFORM:
        raise ValueError(f"checkpoint {checkpoint} has an incompatible target transform")
    backbone = C.BackboneConfig(**payload["backbone_cfg"])
    model = C.ContinuousHeuristicModel(
        backbone,
        token_dim=int(payload["state_cfg"]["token_dim"]),
        max_norm_residual=float(payload["max_log_residual"]),
    )
    model.load_state_dict(payload["model"], strict=True)
    model.to(device).eval()
    return model


# ---------------------------------------------------------------------------
# Euclidean-anchored focal evaluation
# ---------------------------------------------------------------------------


def _search_row(
    base: Mapping[str, Any],
    provider: str,
    mode: str,
    result: Mapping[str, Any],
    optimal: float,
    search_seconds: float,
    focal_w: Optional[float] = None,
    inference_seconds: float = 0.0,
) -> Dict[str, Any]:
    cost = float(result["cost"])
    return {
        **base,
        "provider": provider,
        "mode": mode,
        "focal_w": "" if focal_w is None else float(focal_w),
        "found": bool(result["found"]),
        "expansions": int(result["expansions"]),
        "closed": int(result["closed"]),
        "cost": cost if math.isfinite(cost) else "",
        "cost_ratio": cost / optimal if math.isfinite(cost) and optimal > C.EPS else "",
        "inference_seconds": float(inference_seconds),
        "search_seconds": float(search_seconds),
    }


def _run_astar(
    base: Mapping[str, Any],
    provider: str,
    adj: List[List[Tuple[int, float]]],
    heuristic: np.ndarray,
    budget: int,
    optimal: float,
    inference_seconds: float = 0.0,
) -> Dict[str, Any]:
    t0 = time.perf_counter()
    result = C.astar_search(adj, heuristic, int(budget))
    return _search_row(
        base,
        provider,
        "astar",
        result,
        optimal,
        time.perf_counter() - t0,
        inference_seconds=inference_seconds,
    )

def _run_focal(
    base: Mapping[str, Any],
    provider: str,
    adj: List[List[Tuple[int, float]]],
    euclid: np.ndarray,
    rank: np.ndarray,
    budget: int,
    optimal: float,
    focal_w: float,
    inference_seconds: float = 0.0,
) -> Dict[str, Any]:
    t0 = time.perf_counter()
    result = focal_astar_search(
        adj,
        euclid,
        rank,
        int(budget),
        w=float(focal_w),
    )
    return _search_row(
        base,
        provider,
        "focal",
        result,
        optimal,
        time.perf_counter() - t0,
        focal_w=float(focal_w),
        inference_seconds=inference_seconds,
    )



def summarize_evaluation(rows: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    euclid_expansions: Dict[Tuple[Any, ...], float] = {}
    euclid_focal_expansions: Dict[Tuple[Any, ...], float] = {}
    for row in rows:
        if row.get("provider") == "euclid":
            key = (row["suite"], row["world_index"], row["requested_nodes"], row["budget"])
            euclid_expansions[key] = float(row["expansions"])
        if row.get("provider") == "euclid_focal_rank":
            key = (row["suite"], row["world_index"], row["requested_nodes"], row["budget"], float(row["focal_w"]))
            euclid_focal_expansions[key] = float(row["expansions"])

    grouped: DefaultDict[Tuple[Any, ...], List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        if row.get("provider") == "build_failure":
            continue
        key = (
            row["provider"],
            row["mode"],
            row.get("focal_w", ""),
            row["requested_nodes"],
            row["budget"],
        )
        grouped[key].append(row)

    summary: List[Dict[str, Any]] = []
    for (provider, mode, focal_w, nodes, budget), group in sorted(grouped.items(), key=lambda item: str(item[0])):
        ratios = [float(r["cost_ratio"]) for r in group if r.get("cost_ratio") != ""]
        deltas: List[float] = []
        focal_deltas: List[float] = []
        for row in group:
            match = (row["suite"], row["world_index"], row["requested_nodes"], row["budget"])
            if match in euclid_expansions:
                deltas.append(float(row["expansions"]) - euclid_expansions[match])
            if mode == "focal":
                focal_match = (*match, float(row["focal_w"]))
                if focal_match in euclid_focal_expansions:
                    focal_deltas.append(float(row["expansions"]) - euclid_focal_expansions[focal_match])
        summary.append(
            {
                "provider": provider,
                "mode": mode,
                "focal_w": focal_w,
                "requested_nodes": nodes,
                "budget": budget,
                "worlds": len(group),
                "success_rate": float(np.mean([bool(r["found"]) for r in group])),
                "expansions_mean": float(np.mean([float(r["expansions"]) for r in group])),
                "expansion_delta_vs_euclid_mean": float(np.mean(deltas)) if deltas else "",
                "expansion_delta_vs_euclid_focal_mean": float(np.mean(focal_deltas)) if focal_deltas else "",
                "cost_ratio_mean_success": float(np.mean(ratios)) if ratios else "",
                "inference_seconds_mean": float(np.mean([float(r["inference_seconds"]) for r in group])),
                "search_seconds_mean": float(np.mean([float(r["search_seconds"]) for r in group])),
            }
        )
    return summary


def evaluate_rankers(
    cfg: C13TDConfig,
    checkpoints: Mapping[str, Path],
    device: torch.device,
) -> Dict[str, Path]:
    M7.install_c7_hard_maps()
    specs = C.build_anchor_specs()
    models = {name: load_ranker(cfg, name, path, device) for name, path in checkpoints.items()}
    densities = C13.parse_int_csv(cfg.density_nodes)
    budgets = C13.parse_int_csv(cfg.budgets)
    focal_ws = C13.parse_float_csv(cfg.focal_ws)
    rows: List[Dict[str, Any]] = []

    for suite_idx, suite in enumerate(C13.parse_csv(cfg.eval_suites)):
        if suite not in specs:
            raise KeyError(f"unknown suite {suite!r}; have {sorted(specs)}")
        accepted = 0
        candidate_worlds = int(cfg.eval_worlds) * int(cfg.max_world_retries)
        for _, world, world_seed in C13.iter_worlds(
            specs[suite],
            suite_idx,
            candidate_worlds,
            int(cfg.seed) + 900_000,
            retry=cfg.max_world_retries,
        ):
            roadmaps: Dict[int, Tuple[Optional[C.Roadmap], float]] = {}
            for density in densities:
                t_build = time.perf_counter()
                rm = C.build_prm(
                    world,
                    C.RoadmapConfig(n_nodes=int(density), k_neighbors=int(cfg.roadmap_k)),
                    seed=world_seed + 17,
                )
                roadmaps[int(density)] = (rm, time.perf_counter() - t_build)
            reference = roadmaps.get(int(cfg.train_nodes), (None, 0.0))[0]
            if reference is None:
                continue

            for density in densities:
                rm, build_seconds = roadmaps[int(density)]
                common = {
                    "suite": suite,
                    "world_index": accepted,
                    "world_seed": world_seed,
                    "roadmap_seed": world_seed + 17,
                    "requested_nodes": int(density),
                    "roadmap_k": int(cfg.roadmap_k),
                    "build_seconds": float(build_seconds),
                }
                if rm is None:
                    for budget in budgets:
                        rows.append(
                            {
                                **common,
                                "actual_nodes": 0,
                                "edges": 0,
                                "budget": int(budget),
                                "provider": "build_failure",
                                "mode": "none",
                                "focal_w": "",
                                "found": False,
                                "expansions": 0,
                                "closed": 0,
                                "cost": "",
                                "cost_ratio": "",
                                "inference_seconds": 0.0,
                                "search_seconds": 0.0,
                            }
                        )
                    continue

                euclid = C13.euclidean_to_goal(rm.points, rm.points[1])
                one_step = C13.one_step_euclidean_backup(rm.points, rm.adj)
                oracle = C13._finite_oracle(rm, world.side_len)
                optimal = float(rm.dist_to_goal[0])
                edges = sum(len(a) for a in rm.adj) // 2
                all_features = C13.make_local_state_features(world, rm.points, rm.adj, cfg.state_cfg())
                predictions: Dict[str, Tuple[np.ndarray, float]] = {}
                for model_name, model in models.items():
                    t_infer = time.perf_counter()
                    residual = C.predict_norm_residuals(model, all_features, device, batch_size=512)
                    inference_seconds = time.perf_counter() - t_infer
                    predictions[model_name] = (
                        euclid
                        + float(world.side_len)
                        * np.expm1(np.clip(residual, 0.0, float(cfg.max_norm_residual))),
                        inference_seconds,
                    )

                for budget in budgets:
                    base = {
                        **common,
                        "actual_nodes": len(rm.points),
                        "edges": edges,
                        "budget": int(budget),
                        "optimal_cost_eval_only": optimal,
                    }
                    rows.append(_run_astar(base, "euclid", rm.adj, euclid, budget, optimal))
                    rows.append(_run_astar(base, "one_step", rm.adj, one_step, budget, optimal))
                    rows.append(_run_astar(base, "oracle_eval_only", rm.adj, oracle, budget, optimal))
                    for focal_w in focal_ws:
                        rows.append(
                            _run_focal(
                                base,
                                "euclid_focal_rank",
                                rm.adj,
                                euclid,
                                euclid,
                                budget,
                                optimal,
                                focal_w,
                            )
                        )
                        rows.append(
                            _run_focal(
                                base,
                                "one_step_focal_rank",
                                rm.adj,
                                euclid,
                                one_step,
                                budget,
                                optimal,
                                focal_w,
                            )
                        )
                    for model_name, (rank, inference_seconds) in predictions.items():
                        rows.append(
                            _run_astar(
                                base,
                                f"{model_name}_td_additive_diagnostic",
                                rm.adj,
                                rank,
                                budget,
                                optimal,
                                inference_seconds=inference_seconds,
                            )
                        )
                        for focal_w in focal_ws:
                            t_search = time.perf_counter()
                            result = focal_astar_search(
                                rm.adj,
                                euclid,
                                rank,
                                int(budget),
                                w=float(focal_w),
                            )
                            rows.append(
                                _search_row(
                                    base,
                                    f"{model_name}_td_rank",
                                    "focal",
                                    result,
                                    optimal,
                                    time.perf_counter() - t_search,
                                    focal_w=float(focal_w),
                                    inference_seconds=inference_seconds,
                                )
                            )
            accepted += 1
            if accepted >= int(cfg.eval_worlds):
                break
        if accepted < int(cfg.eval_worlds):
            raise RuntimeError(f"evaluation/{suite} under-filled: {accepted}/{cfg.eval_worlds}")

    results_dir = C13.ensure_dir(Path(cfg.out_dir) / "results")
    raw_path = C13.write_csv(results_dir / "c13_td_evaluation_raw.csv", rows)
    summary_rows = summarize_evaluation(rows)
    summary_path = C13.write_csv(results_dir / "c13_td_evaluation_summary.csv", summary_rows)
    manifest_path = C13.write_json(
        Path(cfg.out_dir) / "evaluation_manifest.json",
        {
            "experiment": "C13-B",
            "config": asdict(cfg),
            "target_source": TARGET_SOURCE,
            "target_aggregation": TARGET_AGGREGATION,
            "target_transform": TARGET_TRANSFORM,
            "shortest_path_target": SHORTEST_PATH_TARGET,
            "oracle_policy_access": ORACLE_POLICY_ACCESS,
            "primary_integration": "euclidean_anchored_focal_rank",
            "same_search_controls": ["euclid_focal_rank", "one_step_focal_rank"],
            "additive_astar_role": "diagnostic_only_no_optimality_claim",
            "dijkstra_role": "roadmap_connectivity_filter_and_evaluation_only",
            "checkpoints": {name: str(path) for name, path in checkpoints.items()},
            "raw": str(raw_path),
            "summary": str(summary_path),
        },
    )
    return {"raw": raw_path, "summary": summary_path, "manifest": manifest_path}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="C13-B local-rollout TD ranker")
    p.add_argument("--mode", choices=("collect", "train", "eval", "full"), default="full")
    p.add_argument("--out-dir", default=C13TDConfig.out_dir)
    p.add_argument("--train-suites", default=C13TDConfig.train_suites)
    p.add_argument("--eval-suites", default=C13TDConfig.eval_suites)
    p.add_argument("--train-worlds", type=int, default=C13TDConfig.train_worlds)
    p.add_argument("--val-worlds", type=int, default=C13TDConfig.val_worlds)
    p.add_argument("--eval-worlds", type=int, default=C13TDConfig.eval_worlds)
    p.add_argument("--train-nodes", type=int, default=C13TDConfig.train_nodes)
    p.add_argument("--density-nodes", default=C13TDConfig.density_nodes)
    p.add_argument("--roadmap-k", type=int, default=C13TDConfig.roadmap_k)
    p.add_argument("--budgets", default=C13TDConfig.budgets)
    p.add_argument("--focal-ws", default=C13TDConfig.focal_ws)
    p.add_argument("--models", default=C13TDConfig.models)
    p.add_argument("--seed", type=int, default=C13TDConfig.seed)
    p.add_argument("--max-world-retries", type=int, default=C13TDConfig.max_world_retries)
    p.add_argument("--sensor-radius-frac", type=float, default=C13TDConfig.sensor_radius_frac)
    p.add_argument("--num-rays", type=int, default=C13TDConfig.num_rays)
    p.add_argument("--ray-steps", type=int, default=C13TDConfig.ray_steps)
    p.add_argument("--max-neighbors", type=int, default=C13TDConfig.max_neighbors)
    p.add_argument("--rollouts-per-start", type=int, default=C13TDConfig.rollouts_per_start)
    p.add_argument("--max-steps-factor", type=int, default=C13TDConfig.max_steps_factor)
    p.add_argument("--rollout-epsilon", type=float, default=C13TDConfig.rollout_epsilon)
    p.add_argument("--rollout-temperature", type=float, default=C13TDConfig.rollout_temperature)
    p.add_argument("--revisit-penalty-frac", type=float, default=C13TDConfig.revisit_penalty_frac)
    p.add_argument("--reverse-penalty-frac", type=float, default=C13TDConfig.reverse_penalty_frac)
    p.add_argument("--max-norm-residual", type=float, default=C13TDConfig.max_norm_residual)
    p.add_argument("--min-labeled-nodes", type=int, default=C13TDConfig.min_labeled_nodes)
    p.add_argument("--batch-size", type=int, default=C13TDConfig.batch_size)
    p.add_argument("--epochs", type=int, default=C13TDConfig.epochs)
    p.add_argument("--lr", type=float, default=C13TDConfig.lr)
    p.add_argument("--weight-decay", type=float, default=C13TDConfig.weight_decay)
    p.add_argument("--grad-clip", type=float, default=C13TDConfig.grad_clip)
    p.add_argument("--hrm-hidden", type=int, default=C13TDConfig.hrm_hidden)
    p.add_argument("--hrm-layers", type=int, default=C13TDConfig.hrm_layers)
    p.add_argument("--hrm-k-step", type=int, default=C13TDConfig.hrm_k_step)
    p.add_argument("--hrm-heads", type=int, default=C13TDConfig.hrm_heads)
    p.add_argument("--onlstm-hidden", type=int, default=C13TDConfig.onlstm_hidden)
    p.add_argument("--onlstm-layers", type=int, default=C13TDConfig.onlstm_layers)
    p.add_argument("--onlstm-chunk-size", type=int, default=C13TDConfig.onlstm_chunk_size)
    p.add_argument("--head-hidden", type=int, default=C13TDConfig.head_hidden)
    p.add_argument("--device", default=C13TDConfig.device)
    p.add_argument("--smoke-test", action="store_true")
    return p.parse_args()


def config_from_args(args: argparse.Namespace) -> C13TDConfig:
    values = vars(args).copy()
    return apply_smoke_overrides(C13TDConfig(**values))


def main() -> None:
    cfg = config_from_args(parse_args())
    out_dir = Path(cfg.out_dir)
    train_path = out_dir / "datasets" / "c13_td_train.npz"
    val_path = out_dir / "datasets" / "c13_td_val.npz"
    model_names = C13.parse_csv(cfg.models)
    device = resolve_device(cfg.device)
    C.set_global_seed(cfg.seed)

    if cfg.mode in {"collect", "full"}:
        train_path = collect_rollout_dataset(
            cfg,
            "train",
            C13.parse_csv(cfg.train_suites),
            cfg.train_worlds,
            seed_offset=0,
        )
        val_path = collect_rollout_dataset(
            cfg,
            "val",
            C13.parse_csv(cfg.train_suites),
            cfg.val_worlds,
            seed_offset=500_000,
        )
        print(f"train={train_path}\nval={val_path}")

    checkpoints: Dict[str, Path] = {}
    if cfg.mode in {"train", "full"}:
        if not train_path.exists() or not val_path.exists():
            raise FileNotFoundError("collect train/validation datasets before training")
        for model_name in model_names:
            checkpoints[model_name] = train_ranker(cfg, model_name, train_path, val_path, device)
            print(f"checkpoint[{model_name}]={checkpoints[model_name]}")
    else:
        checkpoints = {
            model_name: out_dir / "checkpoints" / f"c13_td_{model_name}.pt"
            for model_name in model_names
        }

    if cfg.mode in {"eval", "full"}:
        missing = [str(path) for path in checkpoints.values() if not path.exists()]
        if missing:
            raise FileNotFoundError(f"missing checkpoints: {missing}")
        outputs = evaluate_rankers(cfg, checkpoints, device)
        for key, value in outputs.items():
            print(f"{key}={value}")

    C13.write_json(
        out_dir / "c13_td_manifest.json",
        {
            "experiment": "C13-B",
            "config": asdict(cfg),
            "target_source": TARGET_SOURCE,
            "target_aggregation": TARGET_AGGREGATION,
            "target_transform": TARGET_TRANSFORM,
            "shortest_path_target": SHORTEST_PATH_TARGET,
            "oracle_policy_access": ORACLE_POLICY_ACCESS,
            "status": "completed_requested_mode",
        },
    )


if __name__ == "__main__":
    main()
